---

- name: install the latest version of Squid
  yum:
    name: squid
    state: latest

- name: Enable service Squid
  service:
    name: squid
    enabled: yes

- name: Create SSL directory
  file:
    path: /etc/squid/ssl_cert
    state: directory
    mode: 700
    owner: squid
    group: squid

- name: Generate SSL self-signed certificate
  command: >
    openssl req -x509 -nodes -sha256 -days 7300 -newkey rsa:2048
        -subj "/C=FR/ST=Paris/L=Paris/O=Ministère des armées/CN={{ ansible_fqdn }}"
        -keyout /etc/squid/ssl_cert/{{ ansible_fqdn }}.pem
        -out /etc/squid/ssl_cert/{{ ansible_fqdn }}.pem
  args:
    creates: "/etc/squid/ssl_cert/{{ ansible_fqdn }}.pem"

- name: Validate private key file permissions
  file:
    path: "/etc/squid/ssl_cert/{{ ansible_fqdn }}.pem"
    owner: "root"
    group: "root"
    mode: '0440'

- name: Ensure CA file available in der format
  command: >
    openssl x509 -in /etc/squid/ssl_cert/{{ ansible_fqdn }}.pem
        -outform DER
        -out /etc/squid/ssl_cert/{{ ansible_fqdn }}.der
  args:
    creates: "/etc/squid/ssl_cert/{{ ansible_fqdn }}.der"

- name: Create var/lib/squid
  file:
    path: /var/lib/squid
    state: directory
    mode: 755
    owner: root
    group: root

- name: Create SSL cache directory
  command: >
    /usr/lib64/squid/ssl_crtd -c -s /var/lib/squid/ssl_db -M 4MB && chown squid:squid -R /var/lib/squid
  args:
    creates: "/var/lib/squid/ssl_db"

- name: Install squid.conf
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: squid
    mode: 0644
    validate: squid -k parse -f %s
  notify:
    - restart squid

- name: Install the latest version of SquidGuard
  yum:
    name: squidGuard
    state: latest
    enablerepo: "epel"

- name: Install squidGuard.conf
  template:
    src: squidGuard.conf.j2
    dest: /etc/squid/squidGuard.conf
    owner: root
    group: squid
    mode: 0644

- name: Open Firewall for Squid
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 3128/tcp
    - 3128/udp
  when: squid_param_firewall

- block:
  - name: Stopping Squid
    service:
      name: squid
      state: stopped

  - name: Remove cache
    file:
      state: "{{ item }}"
      path: "/var/spool/squid/"
      owner: squid
      group: squid
      mode: 0755
    with_items:
      - absent
      - directory

  - name: Create cache
    shell: squid -z
    notify:
      - restart squid
  when: squid_clean_cache

