---

- name: install the latest version of Squid
  yum:
    name: squid
    state: latest

- name: Enable service Squid
  service:
    name: squid
    enabled: yes

- name: Install squid.conf
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: squid
    mode: 0644
    validate: squid -k parse -f %s
  notify:
    - restart squid
