---

- name: include OS family/distribution specific variables
  include_vars: "{{ role_path }}/defaults/{{ ansible_os_family | lower }}.yml"
  when: oracle_java_use_defaults
  tags: [ installation ]

- name: include OS family/distribution specific task file
  include: "{{ ansible_os_family | lower }}/main.yml"
  tags: [ installation ]


