- name: packages | upgrade packages
  apt: 
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600

- name: packages | apt autoremove
  apt:
    autoremove: yes
    
- name: packages | Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - bzip2
    - python-pip
    
