---
- name: Install the latest version of Webmin
  yum:
    name: webmin
    state: latest

- name: Install Calamaris
  yum:
    name: calamaris
    state: latest

- name: Open Firewall
  firewalld:
    port: 10000/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: squid_param_firewall
