#cloud-config

runcmd:
  - sudo sysctl -w net.ipv4.ip_forward=1
  - sudo sed -i '29i net.ipv4.ip_forward=1' /etc/sysctl.conf
  - sudo echo 192.168.0.10 openstack-controller >> /etc/hosts
  - sudo chmod -R 755 /home/temp
  - cd /home/temp
  - . kubespray.conf
  - ./install-ubuntu-18.04.sh $IPA_SERVER_IP $IPA_SERVER_FQDN $IPA_DOMAIN_NAME $IPA_REALM $IPA_PRINCIPAL $IPA_PASSWORD
  - sudo rm -R /home/temp
