#cloud-config

write_files:
  - content: |
          export IPA_SERVER_IP=10.0.0.1
          export IPA_SERVER_FQDN=ipaserver.peploleum.com
          export IPA_DOMAIN_NAME=peploleum.com
          export IPA_REALM=PEPLOLEUM.COM
          export IPA_PRINCIPAL=admin
          export IPA_PASSWORD=adminadmin
    path: /home/temp/ipa.conf
    permissions: '0755'

runcmd:
  - sudo sysctl -w net.ipv4.ip_forward=1
  - sudo sed -i '29i net.ipv4.ip_forward=1' /etc/sysctl.conf
  - sudo echo 192.168.0.10 openstack-controller >> /etc/hosts
  - git clone https://github.com/peploleum/deeploy.git /home/temp/deeploy/
  - sudo chown ubuntu:ubuntu /home/temp/ -R
  - . /home/temp/ipa.conf
  - /home/temp/deeploy/freeipa/client/install-ubuntu-18.04.sh $IPA_SERVER_IP $IPA_SERVER_FQDN $IPA_DOMAIN_NAME $IPA_REALM $IPA_PRINCIPAL $IPA_PASSWORD
