#cloud-config

write_files:
  - content: |
          export IPA_SERVER_IP=##IPA_SERVER_IP##
          export IPA_SERVER_FQDN=##IPA_SERVER_FQDN##
          export IPA_DOMAIN_NAME=##IPA_DOMAIN_NAME##
          export IPA_REALM=##IPA_REALM##
          export IPA_PRINCIPAL=##IPA_PRINCIPAL##
          export IPA_PASSWORD=##IPA_PASSWORD##
    path: /home/temp/ipa.conf
    permissions: '0755'
  - content: |4
        network:
            version: 2
            ethernets:
                ens3:
                    nameservers:
                        search: [##IPA_DOMAIN_NAME##]
    path: /etc/netplan/51-freeipa-dns.yaml
    permissions: '0644'
    owner: root:root

runcmd:
  - sudo echo 192.168.0.10 openstack-controller >> /etc/hosts
  - sudo netplan generate
  - sudo netplan apply
  - git clone https://github.com/peploleum/deeploy.git /home/temp/deeploy/
  - sudo chown ubuntu:ubuntu /home/temp/ -R
  - . /home/temp/ipa.conf
  - /home/temp/deeploy/freeipa/client/install-ubuntu-18.04.sh $IPA_SERVER_IP $IPA_SERVER_FQDN $IPA_DOMAIN_NAME $IPA_REALM $IPA_PRINCIPAL $IPA_PASSWORD
  - sudo rm -R /home/temp
