#!/usr/bin/env bash

docker build -t $DOCKER_PRIVATE_REGISTRY_ENDPOINT/python:3.6.8-alpine3.9 --build-arg IMAGE=$DOCKER_PRIVATE_REGISTRY_ENDPOINT/python:3.6.8-alpine3.9 .
docker login $DOCKER_PRIVATE_REGISTRY_ENDPOINT -u $DOCKER_PRIVATE_REGISTRY_USER -p $DOCKER_PRIVATE_REGISTRY_PASSWORD
docker push $DOCKER_PRIVATE_REGISTRY_ENDPOINT/python:3.6.8-alpine3.9
