---
- name: Install and configure gitlab
  hosts: all

  become: true
  become_method: sudo
  gather_facts: false

  vars:
    docker_user: target

  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
    - name: Install docker and docker-compose
      script: ./scripts/install_docker.sh {{ docker_user }}



