version: "2.0"
services:
  gitlab:
    build:
      context: ./src
    container_name: gitlab 
    restart: always
    hostname: gitlab.peploleum.com
    ports:
    - "9022:22"
    - "9080:9080"
    - "9443:443"
    volumes:
    - ./srv/data:/var/opt/gitlab
    - ./srv/logs:/var/log/gitlab
    - ./srv/config:/etc/gitlab
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://localhost'
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
    - ./srv/git-runner/config:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#    - CI_SERVER_URL=http://gitlab:80/
#    - REGISTRATION_TOKEN=M_wupo5JY5E-dUh6-iPu
#    - RUNNER_NAME=yummy_runner
#    - RUNNER_EXECUTOR=docker
#    - DOCKER_IMAGE=python:2.7.12-alpine
