- name: restart stack
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - postfix 
    - postgresql 
    - nginx 
    - php7.2-fpm 
    - uwsgi 
    - dovecot 
    - clamav-daemon 
    - amavis 
    - clamav-freshclam 
    - sogo 
    - memcached 

- name: restart iredapd
  systemd:
    name: iredapd
    state: restarted
