---

- name: install the latest version of SquidGuard
  yum:
    name: squidGuard
    state: latest
    enablerepo: "epel"

- name: Install squidGuard.conf
  template:
    src: squidGuard.conf.j2
    dest: /etc/squid/squidGuard.conf
    owner: root
    group: squid
    mode: 0644

