---
nexus_download_dir: '/tmp'
nexus_version: '3.15.2-01'
nexus_package: 'nexus-{{ nexus_version }}-unix.tar.gz'
nexus_download_url: 'https://sonatype-download.global.ssl.fastly.net/repository/repositoryManager/3/{{ nexus_package }}'
nexus_installation_dir: '/usr/share'
nexus_working_dir: '/var/nexus'
nexus_port: 9999
nexus_create_os_user: true
nexus_os_user: 'nexus'
nexus_create_os_group: "{{ nexus_create_os_user | bool }}"
nexus_os_group: 'nexus'
nexus_os_user_shell: '/bin/bash'
